version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        environment:
            WWWUSER: "${WWWUSER:-1000}"
        depends_on:
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-root}"
            MYSQL_DATABASE: "wims"
            MYSQL_USER: "comsci"
            MYSQL_PASSWORD: "123456"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ""
        ports:
            - "8080:80"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mysql_data:
